/* Generated by tex3ds */
#pragma once

#define Tile_TileCursor_idx 0
#define Tile_TileDown_idx 1
#define Tile_TileNone_idx 2
#define Tile_TileShadow_idx 3
#define Tile_TileUp_idx 4
#define Tile_TileFlash_idx 5
